CodeSourcePath = "../"

Vagrant::Config.run do |config|
    config.vm.host_name = "jenkinslight"
    
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :hostonly, "10.0.0.2", :netmask => "255.255.255.0"
    config.vm.forward_port 9000, 8888

    config.vm.provision :shell, path: "Vagrantbootstrap.sh"
    config.vm.share_folder("vagrant-root", "/vagrant", CodeSourcePath, :nfs => true)

    config.vm.customize ["modifyvm", :id, "--memory", 1024]
    config.vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    config.vm.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
end